name: "Samsung Frame TV Art Changer"
description: "Automatically downloads and displays artwork on your Samsung Frame TV from Google Art, Bing Wallpapers, or your local media folder."
version: "1.0.8"
url: "https://github.com/williamx98/samsung-frame-tv-art-changer"
slug: "hass-frametv-artchanger"
init: false
startup: once
boot: manual
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - "media:rw"
options:
  tv: "192.168.1.58"
  google_art: false
  download_high_res: true
  wallhaven_wallpapers: true
  wallhaven_url: "https://wallhaven.cc/api/v1/search?q=landscape+photo&categories=101&purity=100&atleast=3840x2160&topRange=1M&sorting=toplist&order=desc&ai_art_filter=1"
  media_folder: false
  same_image: false
schema:
  tv: "str?"
  google_art: "bool?"
  download_high_res: "bool?"
  wallhaven_wallpapers: "bool?"
  wallhaven_url: "str?"
  media_folder: "bool?"
  same_image: "bool?"
image: williamx98/{arch}-samsung-frame-tv-art-changer